### ISSUE TITLE
Error on aarch64 compiling

### ISSUE THREAD

**Issue by Gigaudio** [Irqbalance/irqbalance#353]
Hi,

Using Slackwareaarch64-current, gcc version 15.2.0. I use this SlackBuild with irqbalance 1.9.4:
https://slackbuilds.org/repository/15.0/system/irqbalance/

The error:
> gcc -DHAVE_CONFIG_H -I.  -I. -W -Wall -Wshadow -Wformat -Wundef -D_GNU_SOURCE   -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -c -o procinterrupts.o procinterrupts.c
/bin/sh ./libtool  --tag=CC   --mode=link gcc  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2   -o irqbalance activate.o bitmap.o classify.o cputree.o irqbalance.o irqlist.o numa.o placement.o procinterrupts.o  -lcap-ng -lglib-2.0   -lm  -lncursesw -ltinfo
libtool: link: gcc -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -O2 -o irqbalance activate.o bitmap.o classify.o cputree.o irqbalance.o irqlist.o numa.o placement.o procinterrupts.o  -lcap-ng -lglib-2.0 -lm -lncursesw -ltinfo
gcc -DHAVE_CONFIG_H -I.  -I. -W -Wall -Wshadow -Wformat -Wundef -D_GNU_SOURCE   -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -c -o ui/helpers.o ui/helpers.c
gcc -DHAVE_CONFIG_H -I.  -I. -W -Wall -Wshadow -Wformat -Wundef -D_GNU_SOURCE   -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -c -o ui/irqbalance-ui.o ui/irqbalance-ui.c
ui/irqbalance-ui.c:490:5: error: conflicting types for ‘main’; have ‘int(int,  char **)’
  490 | int main(int argc, char **argv)
      |     ^~~~
In file included from ui/irqbalance-ui.c:14:
ui/irqbalance-ui.h:86:5: note: previous declaration of ‘main’ with type ‘int(void)’
   86 | int main();
      |     ^~~~
make[2]: *** [Makefile:600: ui/irqbalance-ui.o] Error 1
make[2]: Leaving directory '/tmp/SBo/irqbalance-1.9.4'
make[1]: *** [Makefile:667: all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/irqbalance-1.9.4'

**Comment by nhorman** [comment]
this was fixed in commit b6a831d692ed7e12db7748db49b3b39516d151d2, and will be part of the next irqbalance release
